apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingapp-deploy
  labels:
    app: bankapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp-container
        image: alekhya83/bankingapp1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankingapp-np-service
  labels:
    app: bankapp
spec:
  selector:
    app: bankapp

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
